[package]
name = "uihlog"
version = "0.2.0"
authors = ["Yin Gang <gang.yin@united-imaging.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"